import { Sidebar } from '@/containers/Sidebar'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import React from 'react'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='ja'>
      <body>
        <div style={{ display: 'flex', backgroundColor: '#1a1a1a', width: '100vw', height: '100vh' }}>
          <Sidebar />
          <main style={{ padding: '30px 20px 30px 45px', width: '100%' }}>{children}</main>
        </div>
      </body>
    </html>
  )
}
